CREATE OR REPLACE PROCEDURE STATUS_UPDATE(p_project_id INT, p_new_status VARCHAR(50))
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE PROJECT SET PROJECT_STATUS = p_new_status WHERE PROJECT_ID = p_project_id;

    INSERT INTO PROJECT_STATUS_HISTORY (PROJECT_ID, PROJECT_STATUS, CHANGE_DATE)
    VALUES (p_project_id, p_new_status, CURRENT_DATE);
END; $$