CREATE OR REPLACE FUNCTION TOTAL_COST(p_project_id INT) RETURNS NUMERIC
LANGUAGE plpgsql
AS $$
DECLARE
    total_cost NUMERIC;
BEGIN
    SELECT SUM(MATERIAL.METERIAL_COST) INTO total_cost
    FROM MATERIAL
    JOIN PROJECT_MATERIAL ON MATERIAL.MATERIAL_ID = PROJECT_MATERIAL.MATERIAL_ID
    WHERE PROJECT_MATERIAL.PROJECT_ID = p_project_id;
    RETURN total_cost;
END; $$
