CREATE INDEX IDX_PROJECT_NAME ON PROJECT (PROJECT_NAME);
CREATE INDEX IDX_WORKER_NAME_SURNAME ON WORKER (WORKER_NAME, WORKER_SURNAME);
CREATE INDEX IDX_MATERIAL_NAME ON MATERIAL (MATERIAL_NAME);
CREATE INDEX IDX_CLIENT_NAME_SURNAME ON CLIENT (CLIENT_NAME, CLIENT_SURNAME);
CREATE INDEX IDX_ORDER_PROJECT_ID ON ORDER (PROJECT_ID);
