DROP VIEW IF EXISTS Projects_Clients;
CREATE VIEW Projects_Clients AS
SELECT P.PROJECT_ID, P.PROJECT_NAME, P.PROJECT_START, P.PROJECT_END, P.PROJECT_STATUS, C.CLIENT_NAME, C.CLIENT_SURNAME
FROM PROJECT P
JOIN CLIENT C ON P.CLIENT_ID = C.CLIENT_ID;

DROP VIEW IF EXISTS Workers_Projects;
CREATE VIEW Workers_Projects AS
SELECT W.WORKER_NAME, W.WORKER_SURNAME, P.PROJECT_NAME
FROM WORKER W
JOIN PROJECT_WORKER PW ON W.WORKER_ID = PW.WORKER_ID
JOIN PROJECT P ON PW.PROJECT_ID = P.PROJECT_ID;

DROP VIEW IF EXISTS Orders_Materials;
CREATE VIEW Orders_Materials AS
SELECT O.ORDER_ID, M.MATERIAL_NAME, M.METERIAL_COST
FROM ORDER O
JOIN ORDER_MATERIAL OM ON O.ORDER_ID = OM.ORDER_ID
JOIN MATERIAL M ON OM.MATERIAL_ID = M.MATERIAL_ID;
